// All content below is sample data for the SavePaws demo build.
// Photos are pulled from loremflickr, so every reload shows a real photo.

export const photo = (topic, lock, w = 800, h = 900) =>
  `https://loremflickr.com/${w}/${h}/${topic}?lock=${lock}`;

export const animals = [
  {
    id: 'a1',
    name: 'Barnaby',
    species: 'Dog',
    breed: 'Staffordshire mix',
    age: '4 yrs',
    size: 'Medium',
    sex: 'Male',
    shelter: 'Ridgeway Kennels',
    daysWaiting: 214,
    urgent: true,
    tags: ['Good with kids', 'House trained', 'Knows 6 commands'],
    fee: 95,
    photo: photo('staffordshire,dog', 11),
    note: 'Came in with a broken hip after a hit and run. Walks fine now, still flinches at cars, so a quiet street suits him best.',
  },
  {
    id: 'a2',
    name: 'Olive',
    species: 'Cat',
    breed: 'Domestic shorthair',
    age: '2 yrs',
    size: 'Small',
    sex: 'Female',
    shelter: 'Marlow Cattery',
    daysWaiting: 38,
    urgent: false,
    tags: ['Bonded with Fig', 'Lap cat', 'Indoor only'],
    fee: 60,
    photo: photo('tabby,cat', 22),
    note: 'Adopted as a pair with her brother Fig. She talks. Constantly. About everything.',
  },
  {
    id: 'a3',
    name: 'Fig',
    species: 'Cat',
    breed: 'Domestic shorthair',
    age: '2 yrs',
    size: 'Small',
    sex: 'Male',
    shelter: 'Marlow Cattery',
    daysWaiting: 38,
    urgent: false,
    tags: ['Bonded with Olive', 'Shy at first', 'Indoor only'],
    fee: 60,
    photo: photo('black,cat', 33),
    note: 'Hides for the first week, then decides you are furniture and sleeps on you.',
  },
  {
    id: 'a4',
    name: 'Juniper',
    species: 'Dog',
    breed: 'Border collie',
    age: '1 yr',
    size: 'Medium',
    sex: 'Female',
    shelter: 'Ridgeway Kennels',
    daysWaiting: 12,
    urgent: false,
    tags: ['High energy', 'Needs a job', 'Great recall'],
    fee: 120,
    photo: photo('border,collie', 44),
    note: 'Surrendered by a family who underestimated a collie. She needs two hours a day and a puzzle to solve.',
  },
  {
    id: 'a5',
    name: 'Doris',
    species: 'Dog',
    breed: 'Beagle',
    age: '9 yrs',
    size: 'Small',
    sex: 'Female',
    shelter: 'Halden Farm Rescue',
    daysWaiting: 341,
    urgent: true,
    tags: ['Senior', 'Sofa specialist', 'Free adoption'],
    fee: 0,
    photo: photo('beagle', 55),
    note: 'Nine years old and passed over 40 times. Sleeps 18 hours a day and asks for very little.',
  },
  {
    id: 'a6',
    name: 'Pepper',
    species: 'Rabbit',
    breed: 'Lop',
    age: '3 yrs',
    size: 'Small',
    sex: 'Female',
    shelter: 'Halden Farm Rescue',
    daysWaiting: 67,
    urgent: false,
    tags: ['Litter trained', 'Needs a companion', 'Indoor hutch'],
    fee: 35,
    photo: photo('rabbit,lop', 66),
    note: 'An Easter present that stopped being interesting by June. She is still lovely.',
  },
  {
    id: 'a7',
    name: 'Atlas',
    species: 'Dog',
    breed: 'German shepherd',
    age: '6 yrs',
    size: 'Large',
    sex: 'Male',
    shelter: 'Ridgeway Kennels',
    daysWaiting: 156,
    urgent: true,
    tags: ['Ex working dog', 'No small pets', 'Crate trained'],
    fee: 110,
    photo: photo('german,shepherd', 77),
    note: 'Retired from search work after a shoulder injury. Sharp, loyal, and bored out of his mind in a kennel.',
  },
  {
    id: 'a8',
    name: 'Marzipan',
    species: 'Cat',
    breed: 'Ragdoll cross',
    age: '5 mo',
    size: 'Small',
    sex: 'Female',
    shelter: 'Marlow Cattery',
    daysWaiting: 9,
    urgent: false,
    tags: ['Kitten', 'Fully vaccinated', 'Climbs curtains'],
    fee: 75,
    photo: photo('kitten', 88),
    note: 'Found in a car engine bay in March. Now weighs 2.1kg and fears nothing.',
  },
  {
    id: 'a9',
    name: 'Tuesday',
    species: 'Dog',
    breed: 'Lurcher',
    age: '3 yrs',
    size: 'Large',
    sex: 'Female',
    shelter: 'Halden Farm Rescue',
    daysWaiting: 88,
    urgent: false,
    tags: ['Quiet', 'Cat friendly', 'Loves a blanket'],
    fee: 95,
    photo: photo('lurcher,greyhound', 99),
    note: 'Named after the day she was found. Runs for four minutes, sleeps for eleven hours.',
  },
  {
    id: 'a10',
    name: 'Bruno',
    species: 'Dog',
    breed: 'Labrador',
    age: '7 yrs',
    size: 'Large',
    sex: 'Male',
    shelter: 'Ridgeway Kennels',
    daysWaiting: 45,
    urgent: false,
    tags: ['Great with dogs', 'On a diet', 'Steals socks'],
    fee: 90,
    photo: photo('labrador', 101),
    note: 'His owner moved into care. Bruno is 6kg overweight and on a strict plan he resents deeply.',
  },
  {
    id: 'a11',
    name: 'Saffron',
    species: 'Cat',
    breed: 'Ginger tabby',
    age: '4 yrs',
    size: 'Small',
    sex: 'Female',
    shelter: 'Marlow Cattery',
    daysWaiting: 122,
    urgent: true,
    tags: ['FIV positive', 'Indoor only', 'Very affectionate'],
    fee: 0,
    photo: photo('ginger,cat', 111),
    note: 'FIV positive cats live full normal lives indoors. Most people scroll past her anyway.',
  },
  {
    id: 'a12',
    name: 'Clover',
    species: 'Rabbit',
    breed: 'Dutch',
    age: '1 yr',
    size: 'Small',
    sex: 'Male',
    shelter: 'Halden Farm Rescue',
    daysWaiting: 21,
    urgent: false,
    tags: ['Bonded pair wanted', 'Neutered', 'Hay obsessed'],
    fee: 35,
    photo: photo('dutch,rabbit', 121),
    note: 'Would happily share a hutch with Pepper if someone takes them both.',
  },
];

export const campaigns = [
  {
    id: 'c1',
    title: 'Winter kennel heating',
    location: 'Ridgeway Kennels',
    raised: 18400,
    goal: 26000,
    donors: 412,
    daysLeft: 19,
    blurb:
      'Six of the twelve kennel blocks still run on portable heaters from 2009. Replacing them keeps 84 dogs above 15C through January.',
    photo: photo('kennel,dog', 131, 900, 600),
  },
  {
    id: 'c2',
    title: 'Mobile spay and neuter van',
    location: 'County wide',
    raised: 61250,
    goal: 75000,
    donors: 1893,
    daysLeft: 41,
    blurb:
      'One van covers eleven rural postcodes with no low cost clinic. Every 1,000 procedures prevents an estimated 6,700 unwanted births over five years.',
    photo: photo('veterinarian,dog', 141, 900, 600),
  },
  {
    id: 'c3',
    title: 'Emergency intake after the floods',
    location: 'Halden Farm Rescue',
    raised: 9120,
    goal: 12000,
    donors: 276,
    daysLeft: 6,
    blurb:
      'Thirty one animals arrived in nine days when the river came up. This covers their food, medication and quarantine housing.',
    photo: photo('flood,rescue,dog', 151, 900, 600),
  },
  {
    id: 'c4',
    title: 'Senior dog dental fund',
    location: 'All shelters',
    raised: 4780,
    goal: 15000,
    donors: 158,
    daysLeft: 63,
    blurb:
      'Dental disease is the single most common reason an older dog gets passed over. A clean and extraction runs about 380 dollars per dog.',
    photo: photo('senior,dog', 161, 900, 600),
  },
];

export const impact = [
  { value: 6300000, suffix: '', label: 'companion animals entering shelters each year' },
  { value: 4100000, suffix: '', label: 'of those adopted into a home' },
  { value: 920000, suffix: '', label: 'still euthanised, mostly for space' },
  { value: 87, suffix: '%', label: 'of shelter intake is preventable with spay and neuter access' },
];

export const research = [
  {
    stat: '3.1x',
    claim:
      'Households that foster before adopting are three times more likely to complete an adoption than households that meet an animal only at a kennel visit.',
    source: 'Sample figure, SavePaws intake review 2024',
  },
  {
    stat: '48 days',
    claim:
      'A single professional photograph cuts the average time a dog waits for a home from 96 days to 48. It is the cheapest thing a shelter can do.',
    source: 'Sample figure, shelter listing study',
  },
  {
    stat: '1 in 4',
    claim:
      'One in four surrenders is financial, not behavioural. A short term food and vet bank keeps those animals in the homes they already have.',
    source: 'Sample figure, regional surrender survey',
  },
];

export const roles = [
  {
    id: 'r1',
    title: 'Dog walker',
    commitment: '2 hours, weekly',
    spots: 14,
    detail:
      'Two walks per shift from Ridgeway Kennels. Training is one Saturday morning. You will be matched to dogs that suit your pace, not the other way round.',
  },
  {
    id: 'r2',
    title: 'Foster carer',
    commitment: '2 to 8 weeks',
    spots: 6,
    detail:
      'We cover food, crates and every vet bill. You cover the sofa. Most needed for kittens under 8 weeks and dogs recovering from surgery.',
  },
  {
    id: 'r3',
    title: 'Transport driver',
    commitment: 'On call',
    spots: 9,
    detail:
      'Vet runs, intake pickups and adoption handovers. Fuel is reimbursed at 45c per mile. A hatchback is plenty.',
  },
  {
    id: 'r4',
    title: 'Kennel photographer',
    commitment: '3 hours, monthly',
    spots: 3,
    detail:
      'You shoot, we list. Bring a camera and patience. This role moves more animals than any other on the board.',
  },
];

export const stories = [
  {
    name: 'Marisol and Dot',
    quote:
      'Dot spent eleven months in a kennel because she growled at the assessment. Turns out she just hates clipboards. She has been asleep on my bed for two years now.',
    photo: photo('woman,dog', 171, 500, 500),
    since: 'Adopted March 2023',
  },
  {
    name: 'The Okafor family',
    quote:
      'We fostered two kittens for six weeks so we could see how our son handled it. We failed the foster, obviously. Both cats stayed.',
    photo: photo('family,cat', 181, 500, 500),
    since: 'Adopted August 2024',
  },
];

export const adoptedTicker = [
  'Rufus',
  'Nell',
  'Pickle',
  'Otis',
  'Maple',
  'Bear',
  'Winnie',
  'Sid',
  'Hazel',
  'Moss',
  'Ziggy',
  'Peach',
  'Rye',
  'Cassie',
];

export const donationTiers = [
  { amount: 15, impact: 'Feeds one dog for a week' },
  { amount: 40, impact: 'A full vaccination course for a kitten' },
  { amount: 85, impact: 'One night of emergency intake care' },
  { amount: 150, impact: 'A spay or neuter procedure plus recovery' },
  { amount: 380, impact: 'Dental surgery for a senior dog' },
];
